### ISSUE TITLE
[Bug Report] viplanner and rl-games have different wandb version requirements

### ISSUE THREAD

**Issue by SUTLZY** [leggedrobotics/viplanner#53]
viplanner requires wandb==0.14.0.
rl-games requires wandb>=0.12.11,<0.13.0.

**Comment by pascal-roth** [comment]
Hi @SUTLZY ,

Thanks for using our work. 

I must have missed that version issue. ViPlanner should technically also work with lower wandb versions, at least I don't see any issue right now. In any case, for the installation within isaaclab wandb is not required so that you can also remove it there and remain at the versions required for rlgames.

**Comment by pascal-roth** [comment]
I am closing this issue now as the problem does not seem to have much impact, please reopen in the case that it does affect anything from training to data generation
